name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test-nightly:
    name: test nightly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-09-29
          default: true
          profile: minimal
      - name: miri tests
        env:
          MIRI_FLAGS: -Zmiri-strict-provenance
        run: |
          rustup component add miri
          cargo miri test --no-fail-fast --all-features

  tests:
    strategy:
      fail-fast: false
      matrix:
        rust_version: [1.54, 1.63]
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust_version }}
          default: true
          profile: minimal
          components: rustfmt
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose --no-fail-fast --features macro_rules_attribute,atomic
      - name: Formatting
        run: cargo fmt -- --check
